### ISSUE TITLE
Create Path Planner

### ISSUE THREAD

**Issue by jruths** [Voltron-UTD/meta#13]
The path planner takes in the lanelet sequence and produces a path through the world in terms of a sequence of "waypoints" which becomes the reference trajectory for the steering controller.  This involves integrating the vehicle's localization to fuse the lanelet representation of where it needs to go with the real world coordinates.  It also needs to build a path to achieve the lanelet sequence that starts from the vehicle's current location (so needs it's position).

Eventually the path planner will also take in other perception data to identify obstacles, people, stop signs, etc.  This perception data will require the path planner to do some more elaborate planning to figure out how to achieve the lanelet steps as closely as possible without running into anything (so deviations to the lanelet steps might be necessary to avoid a parked car, etc).  In this demo, however, the path planner will pretty much just stick to following the lanelet steps.

**Comment by wheitman** [comment]
Here are some relevant links:
- [Autoware behavior planner node design](https://autowarefoundation.gitlab.io/autoware.auto/AutowareAuto/behavior-planner-node.html)
- [Behavior planner node source code (.cpp)](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/src/planning/behavior_planner_nodes/src/behavior_planner_node.cpp)
- [Standard definition of a path planner (vs. route planner), ***section 4.2***](https://arxiv.org/pdf/1901.04407.pdf)
   - This paper also discusses a *behavior selector*, which broadly selects a path and attaches a velocity to it to form a *goal*. It appears that Autoware combines the standard path planner and behavior selector into a "behavior planner."

Also note that the path planner depends on semantic map data! Autoware.Auto uses the Lanelet2 format to store and represent semantic maps. So we'll need a semantic map of our test area to get very far with path planning...

**Comment by wheitman** [comment]
Path planning now successfully implemented via [Demo 0a](https://github.com/Voltron-UTD/demo_0/blob/main/0v1_steps.md).
