### ISSUE TITLE
Code LIDAR interface nodes for ROS

### ISSUE THREAD

**Issue by wheitman** [Voltron-UTD/meta#5]

**Comment by wheitman** [comment]
Yo @EganJ have you seen [this](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/src/perception/filters/point_cloud_filter_transform_nodes/src/point_cloud_filter_transform_node.cpp#L76) and [this](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/src/perception/filters/point_cloud_filter_transform_nodes/param/vlp16_sim_lexus_filter_transform.param.yaml)? Looks like this is how Autoware filters/transforms data from individual Lidar sensors 🤔

**Comment by EganJ** [comment]
I didn't know about the filter, but saw the transform file. Still have to look in to how to use it, though.

**Comment by EganJ** [comment]
(Moving a summary of updates from Microsoft Teams to here).

A repository has been created for this task: [Voltron-UTD/LidarInterface](https://github.com/Voltron-UTD/LidarInterface). 

Things are pretty well along for a bare-bones lidar interface. A partial stack has been constructed using existing Autoware.Auto code, and an example subscriber to a PointCloud2 topic has been written in case more fine-grain control is needed.

None of the configuration files are accurate and a few things are missing from the stack.

**Comment by wheitman** [comment]
Great, this sounds perfect! Can't wait to see this in action on the car. Maybe we can even create a rosbag at some point of us driving around campus, and share that lidar recording with the planning team for testing.

**Comment by EganJ** [comment]
Was able to use the code from Voltron-UTD/LidarInterface to listen to and merge both lidars at once. There are still a few steps to be done documented on that repository, but this part is nearly to a functional stage.

**Comment by wheitman** [comment]
Perfect! Ideally we can just drop your node into a launch file (sorta like [lines 127-142 here](https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/src/tools/autoware_auto_avp_demo/launch/ms3_vehicle.launch.py#L127)), and it sounds like it's nearly there. Modular code! Once that's working, we can go for a drive and map out campus :)

**Comment by wheitman** [comment]
Successfully implemented and tested via @EganJ 's [LidarInterface repo](https://github.com/Voltron-UTD/LidarInterface) 🎉
